#!/usr/bin/env node

require("adone");
const {
    process: { exec },
    std: { fs }
} = adone;

const fd = fs.openSync(process.argv[2], "w");

const cp = exec("noop", ["foo"], {
    detached: true,
    stdio: ["ignore", fd]
});
cp.unref();

process.exit();
