/**
 * Operator symbols to be used when querying data
 */
const operators = {
    eq: Symbol("eq"),
    ne: Symbol("ne"),
    gte: Symbol("gte"),
    gt: Symbol("gt"),
    lte: Symbol("lte"),
    lt: Symbol("lt"),
    not: Symbol("not"),
    is: Symbol("is"),
    in: Symbol("in"),
    notIn: Symbol("notIn"),
    like: Symbol("like"),
    notLike: Symbol("notLike"),
    iLike: Symbol("iLike"),
    notILike: Symbol("notILike"),
    regexp: Symbol("regexp"),
    notRegexp: Symbol("notRegexp"),
    iRegexp: Symbol("iRegexp"),
    notIRegexp: Symbol("notIRegexp"),
    between: Symbol("between"),
    notBetween: Symbol("notBetween"),
    overlap: Symbol("overlap"),
    contains: Symbol("contains"),
    contained: Symbol("contained"),
    adjacent: Symbol("adjacent"),
    strictLeft: Symbol("strictLeft"),
    strictRight: Symbol("strictRight"),
    noExtendRight: Symbol("noExtendRight"),
    noExtendLeft: Symbol("noExtendLeft"),
    and: Symbol("and"),
    or: Symbol("or"),
    any: Symbol("any"),
    all: Symbol("all"),
    values: Symbol("values"),
    col: Symbol("col"),
    placeholder: Symbol("placeholder"),
    join: Symbol("join"),
    raw: Symbol("raw") // deprecated remove by v5.0
};

const Aliases = {
    $eq: operators.eq,
    $ne: operators.ne,
    $gte: operators.gte,
    $gt: operators.gt,
    $lte: operators.lte,
    $lt: operators.lt,
    $not: operators.not,
    $in: operators.in,
    $notIn: operators.notIn,
    $is: operators.is,
    $like: operators.like,
    $notLike: operators.notLike,
    $iLike: operators.iLike,
    $notILike: operators.notILike,
    $regexp: operators.regexp,
    $notRegexp: operators.notRegexp,
    $iRegexp: operators.iRegexp,
    $notIRegexp: operators.notIRegexp,
    $between: operators.between,
    $notBetween: operators.notBetween,
    $overlap: operators.overlap,
    $contains: operators.contains,
    $contained: operators.contained,
    $adjacent: operators.adjacent,
    $strictLeft: operators.strictLeft,
    $strictRight: operators.strictRight,
    $noExtendRight: operators.noExtendRight,
    $noExtendLeft: operators.noExtendLeft,
    $and: operators.and,
    $or: operators.or,
    $any: operators.any,
    $all: operators.all,
    $values: operators.values,
    $col: operators.col,
    $raw: operators.raw // deprecated remove by v5.0
};

const LegacyAliases = { // deprecated remove by v5.0
    ne: operators.ne,
    not: operators.not,
    in: operators.in,
    notIn: operators.notIn,
    gte: operators.gte,
    gt: operators.gt,
    lte: operators.lte,
    lt: operators.lt,
    like: operators.like,
    ilike: operators.iLike,
    $ilike: operators.iLike,
    nlike: operators.notLike,
    $notlike: operators.notLike,
    notilike: operators.notILike,
    "..": operators.between,
    between: operators.between,
    "!..": operators.notBetween,
    notbetween: operators.notBetween,
    nbetween: operators.notBetween,
    overlap: operators.overlap,
    "&&": operators.overlap,
    "@>": operators.contains,
    "<@": operators.contained
};

operators.Aliases = Aliases;
operators.LegacyAliases = Object.assign({}, LegacyAliases, Aliases);

export default operators;
