stages:
    - test

ubuntu:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - ubuntu

debian:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - debian

freebsd:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - freebsd

osx:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - osx

windows 7:
    stage: test
    script:
        - call npm i
        - call npm run build
        - call npm test glosses
        - call npm test omnitron
    tags:
        - windows 7

windows 8.1:
    stage: test
    script:
        - call npm i
        - call npm run build
        - call npm test glosses
        - call npm test omnitron
    tags:
        - windows 8.1

windows 10:
    stage: test
    script:
        - call npm i
        - call npm run build
        - call npm test glosses
        - call npm test omnitron
    tags:
        - windows 10