stages:
    - test

ubuntu:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test
    tags:
        - ubuntu

debian:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test
    tags:
        - debian

freebsd:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test
    tags:
        - freebsd
