stages:
    - test

ubuntu:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - ubuntu
    only:
        - triggers

debian:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - debian
    only:
        - triggers

freebsd:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - freebsd
    only:
        - triggers

osx:
    stage: test
    script:
        - npm i
        - npm run build
        - npm test glosses
        - npm test omnitron
    tags:
        - osx
    only:
        - triggers

windows 7:
    stage: test
    script:
        - call npm i
        - call npm run build
        - call npm test glosses
        - call npm test omnitron
    tags:
        - windows 7
    only:
        - triggers

windows 8.1:
    stage: test
    script:
        - call npm i
        - call npm run build
        - call npm test glosses
        - call npm test omnitron
    tags:
        - windows 8.1
    only:
        - triggers

windows 10:
    stage: test
    script:
        - call npm i
        - call npm run build
        - call npm test glosses
        - call npm test omnitron
    tags:
        - windows 10
    only:
        - triggers