const core = require("pull-stream");

adone.lazify({
    // // sources
    // keys: "./sources/keys",
    // once: "./sources/once",
    // values: "./sources/values",
    // count: "./sources/count",
    // infinite: "./sources/infinite",
    // empty: "./sources/empty",
    // error: "./sources/error",

    // sinks
    drain: "pull-drain",
    // onEnd: "./sinks/on_end",
    // log: "./sinks/log",
    // find: "./sinks/find",
    // reduce: "./sinks/reduce",
    // collect: "./sinks/collect",
    // concat: "./sinks/concat",

    // // throughs
    // map: "./throughs/map",
    // asyncMap: "./throughs/async_map",
    // filter: "./throughs/filter",
    // filterNot: "./throughs/filter_not",
    // through: "./throughs/through",
    // take: "./throughs/take",
    // unique: "./throughs/unique",
    // nonUnique: "./throughs/non_unique",
    // flatten: "./throughs/flatten",

    // abortable: "./abortable",
    // batch: "./batch",
    // cat: "./cat",
    // catch: "./catch",
    // defer: "./defer",
    // file: "./file",
    // utf8Decoder: "./utf8_decoder",
    // generate: "./generate",
    // handshake: "./handshake",
    // ndjson: "./ndjson",
    // through2: "./through2", // pull-through
    // split: "./split",
    // stringify: "./stringify",
    pushable: "it-pushable",
    // itrPushable: "./itr_pushable",
    // reader: "./reader",
    // pair: "./pair",
    lengthPrefixed: "it-length-prefixed",
    // paramap: "./paramap",
    // pause: "./pause",
    // protocolBuffers: "./protocol_buffers",
    // sort: "./sort",
    // pullStreamToStream: "./pull_stream_to_stream",
    // streamToPullStream: "./stream_to_pull_stream",
    // asyncIteratorToPullStream: "./async_iterator_to_pull_stream",
    // pullStreamToAsyncIterator: "./pull_stream_to_async_iterator",
    // traverse: "./traverse",
    // write: "./write",
    // ws: "./ws",
    // ws2: "./ws2",
    // socketioPullStream: "./socketio_pull_stream",
    // is: "./is",
    // peek: "./peek",
    // hang: "./hang",
    // block: "./block",
    // jsonDoubleline: "./json_doubleline",
    // goodbye: "./goodbye",
    // serializer: "./serializer",
    // many: "./many",
    // pullToStream: "./pull_to_stream",
    // bufferStream: "./buffer_stream",
    // zip: "./zip",
    pipe: "it-pipe"
}, core, require);

export default adone.asNamespace(core);
