#!/bin/bash

### BEGIN INIT INFO
# Provides:          omnitron
# Required-Start:    $remote_fs $local_fs
# Required-Stop:     $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Omnitron service
# Description:       Omnitron service - ADONE execution core
# Author:            Adone Core Team
# Created:           {{created}}
### END INIT INFO

NODE_EXEC=$(which node)
WRAPPER_PATH="{{script}}"
USER={{user}}

case "$1" in
  start) echo "$NODE_EXEC $WRAPPER_PATH start" | sudo -i -u $USER ;;
  stop) echo "$NODE_EXEC $WRAPPER_PATH stop" | sudo -i -u $USER ;;  
  restart) echo "$NODE_EXEC $WRAPPER_PATH restart" | sudo -i -u $USER ;;
  status) echo "$NODE_EXEC $WRAPPER_PATH status" | sudo -i -u $USER ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}" >&2
    exit 3
  ;;
esac
