export const alnum = "a-zA-Z0-9";
export const alpha = "a-zA-Z";
export const ascii = "\\x00-\\x7F";
export const blank = " \\t";
export const cntrl = "\\x00-\\x1F\\x7F";
export const digit = "0-9";
export const graph = "\\x21-\\x7E";
export const lower = "a-z";
export const print = "\\x20-\\x7E ";
export const punct = '\\-!"#$%&\'()\\*+,./:;<=>?@[\\]^_`{|}~';
export const space = " \\t\\r\\n\\v\\f";
export const upper = "A-Z";
export const word = "A-Za-z0-9_";
export const xdigit = "A-Fa-f0-9";
