export default {
    input: "src/glosses/web/browser/core/index.js",
    output: [
        {
            file: "lib/glosses/web/browser/core.mjs",
            format: "esm",
            // paths: (id) => id.startsWith("svelte/") && id.replace("svelte", ".")
        },
        {
            file: "lib/glosses/web/browser/core.js",
            format: "cjs",
            // paths: (id) => id.startsWith("svelte/") && id.replace("svelte", ".")
        }
    ],
    // external: (id) => id.startsWith("svelte/"),
    plugins: [{
        generateBundle(options, bundle) {
            const mod = bundle["core.mjs"];
            if (mod) {
                adone.fs.writeFileSync("src/glosses/web/compiler/compile/internal_exports.ts", `// This file is automatically generated\nexport default new Set(${JSON.stringify(mod.exports)});`);
            }
        }
    }]
};
