adone.lazify({
    EventEmitter: "./events",
    Node: "./node",
    Screen: "./screen",
    canvas: () => adone.lazify({
        Canvas1: "./canvases/canvas1",
        Canvas2: "./canvases/canvas2"
    }, null, require),
    layout: () => adone.lazify({
        Grid: "./layouts/grid",
        Carousel: "./layouts/carousel"
    }, null, require),
    widget: () => adone.lazify({
        Element: "./widgets/element",
        Text: "./widgets/text",
        Line: "./widgets/line",
        ScrollableBox: "./widgets/scrollablebox",
        ScrollableText: "./widgets/scrollabletext",
        BigText: "./widgets/bigtext",
        List: "./widgets/list",
        Form: "./widgets/form",
        Input: "./widgets/input",
        TextArea: "./widgets/textarea",
        TextBox: "./widgets/textbox",
        Button: "./widgets/button",
        ProgressBar: "./widgets/progressbar",
        FileManager: "./widgets/filemanager",
        CheckBox: "./widgets/checkbox",
        RadioSet: "./widgets/radioset",
        RadioButton: "./widgets/radiobutton",
        Prompt: "./widgets/prompt",
        Question: "./widgets/question",
        Message: "./widgets/message",
        Loading: "./widgets/loading",
        ListBar: "./widgets/listbar",
        Log: "./widgets/log",
        Table: "./widgets/table",
        ListTable: "./widgets/listtable",
        Terminal: "./glosses/widgets/Terminal",
        ANSIImage: "./widgets/ansiimage",
        OverlayImage: "./widgets/overlayimage",
        Video: "./widgets/video",
        Layout: "./widgets/layout",
        Grid: "./widgets/grid",
        MultiPage: "./widgets/multipage",
        TabBar: "./widgets/tabbar",
        Canvas: "./widgets/canvas",
        WorldMap: "./widgets/world_map",
        Donut: "./widgets/donut",
        Gauge: "./widgets/gauge",
        GaugeList: "./widgets/gaugelist",
        SparkLine: "./widgets/sparkline",
        ExTable: "./widgets/extable",
        LCD: "./widgets/lcd",
        ExLog: "./widgets/exlog",
        Tree: "./widgets/tree",
        Markdown: "./widgets/markdown",
        Picture: "./widgets/picture",
        BarChart: "./widgets/charts/bar",
        LineChart: "./widgets/charts/line",
        StackedBarChart: "./widgets/charts/stackedbar",
        chart: () => adone.lazify({
            Bar: "./widgets/charts/bar",
            StackedBar: "./widgets/charts/stackedbar",
            Line: "./widgets/charts/line"
        }, null, require)
    }, null, require)
}, adone.asNamespace(exports), require);
