adone.lazify({
    EventEmitter: "./events",
    Node: "./node",
    Screen: "./screen",
    GridLayout: "./layout/grid",
    CarouselLayout: "./layout/carousel",
    Separator: "./prompt/separator",
    Prompt: "./prompt",
    prompt: () => adone.lazify({
        list: "./prompt/species/list",
        input: "./prompt/species/input",
        confirm: "./prompt/species/confirm",
        rawlist: "./prompt/species/rawlist",
        expand: "./prompt/species/expand",
        checkbox: "./prompt/species/checkbox",
        password: "./prompt/species/password",
        editor: "./prompt/species/editor",
        autocomplete: "./prompt/species/autocomplete",
        directory: "./prompt/species/directory"
    }, null, require),
    Progress: "./progress",
    layout: () => adone.lazify({
        Grid: "./layout/grid",
        Carousel: "./layout/carousel"
    }, null, require),
    widget: () => adone.lazify({
        Element: "./widgets/element",
        Text: "./widgets/text",
        Line: "./widgets/line",
        ScrollableBox: "./widgets/scrollablebox",
        ScrollableText: "./widgets/scrollabletext",
        BigText: "./widgets/bigtext",
        List: "./widgets/list",
        Form: "./widgets/form",
        Input: "./widgets/input",
        TextArea: "./widgets/textarea",
        TextBox: "./widgets/textbox",
        Button: "./widgets/button",
        ProgressBar: "./widgets/progressbar",
        FileManager: "./widgets/filemanager",
        CheckBox: "./widgets/checkbox",
        RadioSet: "./widgets/radioset",
        RadioButton: "./widgets/radiobutton",
        Prompt: "./widgets/prompt",
        Question: "./widgets/question",
        Message: "./widgets/message",
        Loading: "./widgets/loading",
        ListBar: "./widgets/listbar",
        Log: "./widgets/log",
        Table: "./widgets/table",
        ListTable: "./widgets/listtable",
        Terminal: "./glosses/widgets/Terminal",
        ANSIImage: "./widgets/ansiimage",
        OverlayImage: "./widgets/overlayimage",
        Video: "./widgets/video",
        Layout: "./widgets/layout",
        Grid: "./widgets/grid",
        MultiPage: "./widgets/multipage",
        TabBar: "./widgets/tabbar",
        Canvas: "./widgets/canvas",
        Map: "./widgets/map",
        Donut: "./widgets/donut",
        Gauge: "./widgets/gauge",
        GaugeList: "./widgets/gaugelist",
        SparkLine: "./widgets/sparkline",
        ExTable: "./widgets/extable",
        LCD: "./widgets/lcd",
        ExLog: "./widgets/exlog",
        Tree: "./widgets/tree",
        Markdown: "./widgets/markdown",
        Picture: "./widgets/picture",
        BarChart: "./widgets/charts/bar",
        LineChart: "./widgets/charts/line",
        StackedBarChart: "./widgets/charts/stackedbar",
        chart: () => adone.lazify({
            Bar: "./widgets/charts/bar",
            StackedBar: "./widgets/charts/stackedbar",
            Line: "./widgets/charts/line"
        }, null, require)
    }, null, require)
}, exports, require);
