#!/usr/bin/env node

require("a"); // adone
const fs = require("fs");

adone.app.run({
    async run() {
        const fd = fs.openSync(process.argv[2], "w");

        const cp = adone.process.exec("noop", ["foo"], {
            detached: true,
            stdio: ["ignore", fd]
        });
        cp.unref();

        return 0;
    }
});
