export const SLEEP = 0x00;  // deprecated
export const QUIT = 0x01;
export const INIT_DB = 0x02;
export const QUERY = 0x03;
export const FIELD_LIST = 0x04;
export const CREATE_DB = 0x05;
export const DROP_DB = 0x06;
export const REFRESH = 0x07;
export const SHUTDOWN = 0x08;
export const STATISTICS = 0x09;
export const PROCESS_INFO = 0x0a;  // deprecated
export const CONNECT = 0x0b;  // deprecated
export const PROCESS_KILL = 0x0c;
export const DEBUG = 0x0d;
export const PING = 0x0e;
export const TIME = 0x0f;  // deprecated
export const DELAYED_INSERT = 0x10;  // deprecated
export const CHANGE_USER = 0x11;
export const BINLOG_DUMP = 0x12;
export const TABLE_DUMP = 0x13;
export const CONNECT_OUT = 0x14;
export const REGISTER_SLAVE = 0x15;
export const STMT_PREPARE = 0x16;
export const STMT_EXECUTE = 0x17;
export const STMT_SEND_LONG_DATA = 0x18;
export const STMT_CLOSE = 0x19;
export const STMT_RESET = 0x1a;
export const SET_OPTION = 0x1b;
export const STMT_FETCH = 0x1c;
export const DAEMON = 0x1d;  // deprecated
export const BINLOG_DUMP_GTID = 0x1e;
export const UNKNOWN = 0xff;  // bad!
