const { lazify } = adone;

lazify({
    $ref: "./dot/ref",
    allOf: "./dot/allOf",
    anyOf: "./dot/anyOf",
    const: "./dot/const",
    contains: "./dot/contains",
    dependencies: "./dot/dependencies",
    enum: "./dot/enum",
    format: "./dot/format",
    items: "./dot/items",
    maximum: "./dot/_limit",
    minimum: "./dot/_limit",
    maxItems: "./dot/_limitItems",
    minItems: "./dot/_limitItems",
    maxLength: "./dot/_limitLength",
    minLength: "./dot/_limitLength",
    maxProperties: "./dot/_limitProperties",
    minProperties: "./dot/_limitProperties",
    multipleOf: "./dot/multipleOf",
    not: "./dot/not",
    oneOf: "./dot/oneOf",
    pattern: "./dot/pattern",
    properties: "./dot/properties",
    propertyNames: "./dot/propertyNames",
    required: "./dot/required",
    uniqueItems: "./dot/uniqueItems",
    validate: "./dot/validate"
}, exports, require);
